spring.application.name=SpringTweet

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Banco em memória
spring.datasource.url=jdbc:h2:mem:tweetdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL (ótimo pra aula)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true